github wf: move script to external file

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -14,6 +14,7 @@ jobs:
     runs-on: ubuntu-22.04
     env:
       KEY_ID: ${{ vars.KALKUN_GITHUB_WORKFLOW_PACKAGER_KEY_FINGERPRINT }}
+      DPUT_CF: /home/runner/dput.cf
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -53,8 +54,7 @@ jobs:
           echo "$PUB_KEY_PASS" | /usr/lib/gnupg/gpg-preset-passphrase --preset "$KEYGRIP"
       - name: Configure dput
         run: |
-          cp -a utils/launchpad/dput.cf ~/.dput.cf
-          sed -i "s/%LAUNCHPAD_USER_NAME%/${{ vars.LAUNCHPAD_USER_NAME }}/" ~/.dput.cf
+          sed "s/%LAUNCHPAD_USER_NAME%/${{ vars.LAUNCHPAD_USER_NAME }}/" utils/launchpad/dput.cf.in > $DPUT_CF
       - name: Set env
         run: |
           echo "DEBEMAIL=packager@kalkun.invalid" >> $GITHUB_ENV
@@ -72,7 +72,18 @@ jobs:
         run: |
           set -x
 
-          # get the packages from debian salsa servers as they have not entered Debian yet
+          # Don't error out to not fail the github job if a dsc is not available anymore.
+          set +e
+
+          # Upload somes dependencies to the "kalkun-build-deps" PPA for focal
+          # debhelper13 for focal (from focal-backports)
+          ./utils/upload_build_deps_to_ppa.sh -d focal http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_13.6ubuntu1~bpo20.04.1.dsc
+
+          # pkg-php-tools for focal (from jammy) - Don't use it, because it requires the dependencies to conform to the new way php-pkg-tools work, and in focal, the packages don't support that.
+          # ./utils/upload_build_deps_to_ppa.sh -d focal http://archive.ubuntu.com/ubuntu/pool/main/p/pkg-php-tools/pkg-php-tools_1.42build1.dsc
+
+          # Error out again
+          set -e
 
           REPOS_TO_BUILD=()
 
@@ -88,190 +99,15 @@ jobs:
           REPOS_TO_BUILD+=("https://salsa.debian.org/bastif/sphinxcontrib-phpdomain")
           REPOS_TO_BUILD+=("https://salsa.debian.org/php-team/pear/php-codeigniter-framework")
 
-          mkdir -p ~/deps
-          cd ~/deps
-
-          DL_DIR="$(realpath .)"
-
-          BUILD_DEPS_DSC=()
-          # debhelper13 for focal (from focal-backports)
-          BUILD_DEPS_DSC+=("focal|http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_13.6ubuntu1~bpo20.04.1.dsc")
-          # pkg-php-tools for focal (from jammy) - Don't use it, because it requires the dependencies to conform to the new way php-pkg-tools work, and in focal, the packages don't support that.
-          #BUILD_DEPS_DSC+=("focal|http://archive.ubuntu.com/ubuntu/pool/main/p/pkg-php-tools/pkg-php-tools_1.42build1.dsc")
-          # Upload somes dependencies to the "kalkun-build-deps" PPA for focal
-
-          for dep in "${BUILD_DEPS_DSC[@]}"; do
-            dep_distrib="$(cut -d "|" -f 1 <<< "$dep")"
-            dep_dsc="$(cut -d "|" -f 2- <<< "$dep")"
-            if [[ $(ubuntu-distro-info --supported) =~ $dep_distrib ]]; then
-              # Don't fail on error (for example in case the URL throws 404 error)
-              set +e
-
-              backportpackage \
-                --upload "kalkun-build-deps" \
-                --yes \
-                --release-pocket \
-                --suffix "~ppa1" \
-                --destination "$dep_distrib" \
-                --key "$KEY_ID" \
-                "$dep_dsc"
-
-              set -e
-            fi
-          done
-
           for repo in "${REPOS_TO_BUILD[@]}"; do
-            repo_dir="$(echo "$repo" | rev | cut -d "/" -f 1 | rev)"
-
-            cd "$DL_DIR"
-            gbp clone "$repo" $repo_dir
-
-            cd "$DL_DIR/$repo_dir"
-            DCH_DISTRIB=$(dpkg-parsechangelog -S Distribution)
-            if [ ${DCH_DISTRIB,,} = "unreleased" ]; then
-              LAST_COMMIT_HASH="$(git rev-parse --short HEAD)"
-              LAST_COMMIT_DATE="$(git log -1 --date=format:%Y%m%d%H%M --format=%cd)"
-              LAST_COMMIT_DATE_H="$(git log -1 --date=format:%Y-%m-%d\ %H:%M --format=%cd)"
-              dch --local "~~${LAST_COMMIT_DATE}.${LAST_COMMIT_HASH}." ""
-              dch "Snapshot based on package source repository at commit $LAST_COMMIT_HASH, dated $LAST_COMMIT_DATE_H."
-              git add debian/changelog
-              git commit -m "update changelog"
-            fi
-
-            gbp export-orig
-            dpkg-buildpackage -d -S --sign-key="$KEY_ID"
-
-            for suite in $(ubuntu-distro-info --supported); do
-
-              if [ "$suite" = "focal" ]; then
-                if [ "$(dpkg-parsechangelog -S Source)" = "php-league-csv" ]; then
-                  # focal runs PHP 7.4, league/csv 9.8.0 is the last version supporting php7.4
-                  git checkout debian/9.8.0-1
-                  gbp export-orig
-                  currently_marked_released=1
-                fi
-
-                sed -i 's/dh-sequence-phpcomposer/pkg-php-tools/' debian/control
-                sed -i 's/\(pkg-php-tools\).*/\1,/' debian/control
-                if grep -q pkg-php-tools debian/control; then
-                  sed -i 's/dh $@/dh $@ --with phpcomposer/' debian/rules
-                fi
-
-                if [ ${DCH_DISTRIB,,} != "unreleased" ] || [ "a$currently_marked_released" = "a1" ]; then
-                  dch --local "~" ""
-                  currently_marked_released=0
-                else
-                  dch --local "~~${suite}" ""
-                fi
-                dch "Fix Build-Depends in d/control & d/rules to work on $suite"
-                dpkg-buildpackage -d -S --sign-key="$KEY_ID"
-              fi
-
-              backportpackage \
-                --upload "${DPUT_UPLOAD_SERVER}" \
-                --yes \
-                --workdir $(mktemp -d /tmp/$(dpkg-parsechangelog -S Source).XXX) \
-                --release-pocket \
-                --suffix "~ppa1" \
-                --destination "$suite" \
-                --key "$KEY_ID" \
-                ../"$(dpkg-parsechangelog -S Source)"_$(dpkg-parsechangelog -S Version).dsc
-
-              if [ "$suite" = "focal" ]; then
-                # Revert the changes for focal
-                git checkout debian/rules debian/control debian/changelog
-                if [ "$(dpkg-parsechangelog -S Source)" = "php-league-csv" ]; then
-                  git checkout debian/latest
-                fi
-              fi
-            done
-
+            ./utils/upload_kalkun_deps_to_ppa.sh -r "$repo" -d "$(ubuntu-distro-info --supported)" -h "${DPUT_UPLOAD_SERVER}"
           done
-
-          cd "$DL_DIR"
-          ls -1 *.dsc
 
       - name: Build kalkun
         run: |
           set -x
 
-          LAST_U_COMMIT_HASH="$(git rev-parse --short HEAD)"
-          LAST_U_COMMIT_DATE="$(git log -1 --date=format:%Y%m%d%H%M --format=%cd)"
-          LAST_U_COMMIT_DATE_H="$(git log -1 --date=format:%Y-%m-%d\ %H:%M --format=%cd)"
-          UVERSION="$(grep kalkun_version application/config/kalkun_settings.php | cut -d "'" -f 4)"
-
-          # Download only the debian folder from debian salsa servers to be able to build kalkun
-          # This adds only the debian folder to $GITHUB_REF_NAME to be able to build the packages
-          git remote add debian https://salsa.debian.org/bastif/kalkun.git
-          git fetch debian
-          git checkout -b debian_branch debian/debian/latest
-          LAST_D_COMMIT_HASH="$(git rev-parse --short HEAD)"
-          LAST_D_COMMIT_DATE="$(git log -1 --date=format:%Y%m%d%H%M --format=%cd)"
-          LAST_D_COMMIT_DATE_H="$(git log -1 --date=format:%Y-%m-%d\ %H:%M --format=%cd)"
-          git checkout $GITHUB_REF_NAME
-          git checkout debian_branch -- debian
-          git status
-
-          if [[ "$(git tag --points-at ${GIT_BRANCH})" != "" ]]; then
-            TAG_VERSION="$(git tag --points-at ${GIT_BRANCH} | sed "s/^v//")"
-            UVERSIONMANGLED=$(echo ${TAG_VERSION} | sed -e "s/-/~/g")
-            dch -v "${UVERSIONMANGLED}-1~${LAST_D_COMMIT_DATE}.${LAST_D_COMMIT_HASH}" --force-bad-version ""
-            dch "Snapshot based on:"
-            dch "  upstream tag v$TAG_VERSION."
-            dch "  debianization from package source repository at commit $LAST_D_COMMIT_HASH, dated $LAST_D_COMMIT_DATE_H."
-            gbp export-orig --no-pristine-tar --upstream-tag=$(git tag --points-at ${GIT_BRANCH}) --compression=xz
-          else \
-            UVERSIONMANGLED=$(echo "${UVERSION}" | sed -e "s/-/~/g" -e "s/~dev/~~dev/")
-            gbp dch \
-              --new-version="${UVERSIONMANGLED}" \
-              --snapshot \
-              --snapshot-number "${LAST_U_COMMIT_DATE}" \
-              --ignore-branch \
-              --no-git-author \
-              --since=HEAD \
-              debian \
-            # Append debian version to version number (this is because we use --snapshot)
-            dch --local "-1~${LAST_D_COMMIT_DATE}.${LAST_D_COMMIT_HASH}" ""
-            dch "Snapshot based on:"
-            dch "  upstream repository at commit $LAST_U_COMMIT_HASH, dated $LAST_U_COMMIT_DATE_H."
-            dch "  debianization from package source repository at commit $LAST_D_COMMIT_HASH, dated $LAST_D_COMMIT_DATE_H."
-            gbp export-orig --no-pristine-tar --upstream-tree=BRANCH --upstream-branch=$(git rev-parse --abbrev-ref HEAD) --compression=xz ; \
-          fi
-
-          git add debian/changelog
-          git commit -m "update changelog"
-          dpkg-buildpackage -d -S --sign-key="$KEY_ID"
-
-          for suite in $(ubuntu-distro-info --supported); do
-            if [ "$suite" = "focal" ]; then
-              sed -i 's/dh-sequence-phpcomposer/pkg-php-tools/' debian/control
-              sed -i 's/\(pkg-php-tools\).*/\1,/' debian/control
-              if grep -q pkg-php-tools debian/control; then
-                sed -i 's/dh $@/dh $@ --with phpcomposer/' debian/rules
-              fi
-
-              sed -i 's/\(php-random-compat\).*/\1,/' debian/control
-
-              dch --local "~~${suite}" ""
-              dch "Fix Build-Depends in d/control & d/rules to work on $suite"
-              dpkg-buildpackage -d -S --sign-key="$KEY_ID"
-            fi
-
-            backportpackage \
-              --upload "${DPUT_UPLOAD_SERVER}" \
-              --yes \
-              --workdir $(mktemp -d /tmp/$(dpkg-parsechangelog -S Source).XXX) \
-              --release-pocket \
-              --suffix "~ppa1" \
-              --destination "$suite" \
-              --key "$KEY_ID" \
-              ../"$(dpkg-parsechangelog -S Source)"_$(dpkg-parsechangelog -S Version).dsc
-
-            if [ "$suite" = "focal" ]; then
-              # Revert the changes for focal
-              git checkout debian/rules debian/control debian/changelog
-            fi
-          done
+          ./utils/upload_kalkun_deps_to_ppa.sh -r "kalkun" -d "$(ubuntu-distro-info --supported)" -h "${DPUT_UPLOAD_SERVER}"
 
       - name: Copy source packages
         if: true == false
